# Intialize

In [1]:
!pip install --no-index tensorflow-gpu

Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic


In [2]:
!pip install --no-index /home/guest139/s3transfer/botocore
!pip install --no-index /home/guest139/s3transfer
!pip install --no-index /home/guest139/sacremoses
!pip install --no-index /home/guest139/transformers

Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing /home/guest139/s3transfer/botocore
  Stored in directory: /tmp/pip-ephem-wheel-cache-2ep3ytav/wheels/fe/ab/37/f8ebb3c769c11a806041a139b0ab3964015975a5bb08071dc6
Successfully built botocore
  Found existing installation: botocore 1.15.37
    Uninstalling botocore-1.15.37:
      Successfully uninstalled botocore-1.15.37
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing /home/guest139/s3transfer
  Stored in directory: /tmp/pip-ephem-wheel-cache-swmvy5dy/wheels/21/b5/7f/8dc1ac8a07cf30a6f8e4c8c6af478ed702be97967619f38b8b
Successfully built s3transfer
  Found existing installation: s3transfer 0.3.3
  

## Load all files

In [3]:
import tensorflow as tf

en_file1 = '../data/train.lang1.no-punctuation/train.lang1'
en_file2 = '../data/train.en.no-punctuation/unaligned.en'
fr_file1 = '../data/train.lang2.no-punctuation/train.lang2'
fr_file2 = '../data/train.fr.no-punctuation/unaligned.fr'
# TODO: exclude the test set

# lang_files = [en_file1, en_file2, fr_file1, fr_file2] TODO
lang_files = [en_file2]

# Tokenize

## Tokenize all files (whole strings (TODO: substrings, capitalization))

In [4]:
from collections import Counter

# Add control tokens
my_counter = Counter()
for i in range(2):
    my_counter.update(["<START>", "<STOP>", "<UNK>", "<MASK>", "<SEP>", "<PAD>"])

In [5]:
def string_to_tokens(raw_string):
    return raw_string.split()

line_lengths = []
for lang_file in lang_files:
    with open(lang_file) as f:
        for line in f:
            tokens = string_to_tokens(line)
            line_lengths += [len(tokens)]
            for token in tokens:
                my_counter.update([token])    

## Keep tokens that occur more than once

In [6]:
import numpy as np
tokens = np.array(list(my_counter.keys()))
frequencies = np.array(list(my_counter.values()))

In [7]:
retained_tokens = tokens[frequencies > 1]

In [8]:
print(len(tokens))
print(len(retained_tokens))

60014
40145


## Create lookup table dict: string -> token

In [9]:
indices = np.array(range(len(retained_tokens)))

In [10]:
indices

array([    0,     1,     2, ..., 40142, 40143, 40144])

In [11]:
my_tokenizer_lut = dict(zip(retained_tokens,indices))

## Define functions for tokenizing, padding

In [12]:
def pad_tokens(token_list, max_length):
    if len(token_list) >= max_length:
        token_list = token_list[:max_length]
        token_list[(max_length-1)] = my_tokenizer_lut["<STOP>"]
    else:
        while len(token_list) < max_length:
            token_list = token_list + [my_tokenizer_lut["<PAD>"]]
    return token_list

SENTENCE_LENGTH = 64
def tokenize_string(raw_string, max_length=SENTENCE_LENGTH): # TODO: Better definition of sentence length
    token_list = [my_tokenizer_lut["<START>"]]
    
    for token in string_to_tokens(raw_string):
        if token in my_tokenizer_lut:
            token_list += [my_tokenizer_lut[token]]
        else:
            token_list += [my_tokenizer_lut["<UNK>"]]
    
    token_list += [my_tokenizer_lut["<STOP>"]]
    
    token_list = pad_tokens(token_list, max_length)
    
    return np.array(token_list)[None,:]
        
tokenize_string("The quick brown fox jumped over the lazy dog.")

array([[    0,     2,   292,  3228,  6307,  2514,   995,     7, 12783,
            2,     1,     5,     5,     5,     5,     5,     5,     5,
            5,     5,     5,     5,     5,     5,     5,     5,     5,
            5,     5,     5,     5,     5,     5,     5,     5,     5,
            5,     5,     5,     5,     5,     5,     5,     5,     5,
            5,     5,     5,     5,     5,     5,     5,     5,     5,
            5,     5,     5,     5,     5,     5,     5,     5,     5,
            5]])

In [13]:
def tokenize_file(filename):
    with open(filename) as f:
        tokens = []
        for idx, line in enumerate(f):
            if idx < 2:
                print(line)
            tokens += [tokenize_string(line)]
    return np.concatenate(tokens,axis=0)

x_true = tokenize_file(en_file2)
x_true_val = tokenize_file(en_file1)
x_true.shape

for the second phase of the trials we just had different sizes small medium large and extra - large it 's true

geng had been my host the previous january when i was the first us defense secretary to visit china acting as an interlocutor for president jimmy carter ’s administration

so too does the idea that accommodating religious differences is dangerous

mr president ladies and gentlemen the financial perspective outlines the scope of the eu ’s activities over coming years as well as providing a framework for such activities and determining how effective they will be



(474000, 64)

# Define masking strategy

In [14]:
def mask_tokens(true_tokens):
    non_pad_tokens = true_tokens != my_tokenizer_lut["<PAD>"]
    random_masking_seed = np.random.uniform(0,1,(SENTENCE_LENGTH,)) * non_pad_tokens
    
    masking_targets = 0.85 < random_masking_seed # 15%
    mask_token_targets = np.logical_and(0.85 < random_masking_seed, random_masking_seed < 0.85 + 0.15*0.8) # 80% of 15%
    random_token_targets = np.logical_and(1.0 - 0.1*0.15 < random_masking_seed, random_masking_seed < 1.0) # 10% of 15%
    
    masked_tokens = true_tokens.copy()
    masked_tokens[mask_token_targets] = my_tokenizer_lut["<MASK>"]
    masked_tokens[random_token_targets] = np.random.randint(0,len(my_tokenizer_lut),(random_token_targets.sum(),))
#     masked_tokens[~mask_token_targets] = my_tokenizer_lut["<PAD>"]

    masked_true_tokens = true_tokens.copy()
    masked_true_tokens[~masking_targets] = my_tokenizer_lut["<PAD>"]
    
    attention_mask = true_tokens != my_tokenizer_lut["<PAD>"]
    
    return masked_tokens, masking_targets, masked_true_tokens, attention_mask

x_train, targets_train, masked_x_true, attention_mask = mask_tokens(x_true)
x_train_val, targets_train_val, masked_x_true_val, attention_mask_val = mask_tokens(x_true_val)
x_train[0]

array([ 0,  6,  7,  8,  9, 10,  7, 11, 12, 13, 14, 15,  3,  3, 18, 19,  3,
       21,  3,  3, 23, 24, 25,  1,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5])

In [15]:
targets_train[:2]

array([[False, False, False, False, False, False, False, False, False,
        False, False, False,  True,  True, False, False,  True, False,
         True,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False,  True,  True, False, False,  True, False,
         True,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, Fals

In [16]:
attention_mask[:2]

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, Fals

In [17]:
x_true[:2]

array([[ 0,  6,  7,  8,  9, 10,  7, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 19, 23, 24, 25,  1,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 0,  2, 14, 26, 27, 28,  7, 29, 30, 31, 32, 33,  7, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44,  6, 45, 46, 47, 48, 49,  1,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5]])

# Override model to include masking

In [18]:
from transformers import TFBertForMaskedLM, BertConfig

I0408 20:56:46.205807 47434534466560 file_utils.py:57] TensorFlow version 2.1.0 available.


## Overriding functions

In [19]:
class bert_with_mask(tf.keras.Model):
    def __init__(self, config, onehot_mask):
        super(bert_with_mask, self).__init__()
        self.bert = TFBertForMaskedLM(config)
        self.onehot_mask = onehot_mask

    def call(self, inputs):
        mask = inputs[-1] # unpack mask from inputs
        inputs = inputs[:-1]
        outputs = self.bert(inputs)[0]
        
        outputs = tf.where(mask[:,:,None], outputs, self.onehot_mask[None,None,:])
        
        return (outputs,)

## Define masking function

In [20]:
onehot_mask = np.zeros(len(my_tokenizer_lut), dtype=np.float32)
onehot_mask[my_tokenizer_lut["<PAD>"]] = 1.0

## Test the model

In [21]:
config = BertConfig.from_pretrained('../code/bert_config_tiny.json')
config.vocab_size = len(my_tokenizer_lut)

I0408 20:56:47.542387 47434534466560 configuration_utils.py:281] loading configuration file ../code/bert_config_tiny.json
I0408 20:56:47.545097 47434534466560 configuration_utils.py:319] Model config BertConfig {
  "_num_labels": 2,
  "architectures": null,
  "attention_probs_dropout_prob": 0.1,
  "bad_words_ids": null,
  "bos_token_id": null,
  "decoder_start_token_id": null,
  "do_sample": false,
  "early_stopping": false,
  "eos_token_id": null,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 128,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 512,
  "is_decoder": false,
  "is_encoder_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-12,
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 512,
  "min_length": 0,
  "model_type": "bert",
  "no_repeat_ngram_size": 0,
  "num_attention_heads": 2,
  "num_beam

In [22]:
model2 = bert_with_mask(config, onehot_mask)

optimizer = tf.keras.optimizers.Adam(learning_rate=3e-4, epsilon=1e-08, clipnorm=1.0)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

model2.compile(optimizer=optimizer, loss=loss)

# Define a dataset

In [23]:
BATCH_SIZE = 32
def data_generator_fn():
    for x in x_true:
        x_train, targets_train, masked_x_true, attention_mask = mask_tokens(x)
        yield (x_train, attention_mask, targets_train), masked_x_true

# dataset object
dataset = tf.data.Dataset.from_generator(
    data_generator_fn,
    output_types=((tf.int32, tf.bool, tf.bool), tf.int32),
    output_shapes=(( tf.TensorShape((SENTENCE_LENGTH,)), tf.TensorShape((SENTENCE_LENGTH,)), tf.TensorShape((SENTENCE_LENGTH,)) ), tf.TensorShape((SENTENCE_LENGTH,)) )
)
dataset = dataset.batch(BATCH_SIZE).prefetch(tf.data.experimental.AUTOTUNE)

In [24]:
BATCH_SIZE = 32
def data_generator_fn_val():
    for x in x_true_val:
        x_train, targets_train, masked_x_true, attention_mask = mask_tokens(x)
        yield (x_train, attention_mask, targets_train), masked_x_true

# dataset object
dataset_val = tf.data.Dataset.from_generator(
    data_generator_fn_val,
    output_types=((tf.int32, tf.bool, tf.bool), tf.int32),
    output_shapes=(( tf.TensorShape((SENTENCE_LENGTH,)), tf.TensorShape((SENTENCE_LENGTH,)), tf.TensorShape((SENTENCE_LENGTH,)) ), tf.TensorShape((SENTENCE_LENGTH,)) )
)
dataset_val = dataset_val.batch(BATCH_SIZE).prefetch(tf.data.experimental.AUTOTUNE)

In [ ]:
hist = model2.fit(dataset, validation_data=dataset_val, epochs=10)

Epoch 1/10


/localscratch/guest139.356788.0/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
W0408 20:56:56.682170 47434534466560 optimizer_v2.py:1043] Gradients do not exist for variables ['bert_with_mask/tf_bert_for_masked_lm/bert/pooler/dense/kernel:0', 'bert_with_mask/tf_bert_for_masked_lm/bert/pooler/dense/bias:0'] when minimizing the loss.
/localscratch/guest139.356788.0/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
W0408 20:56:59.367838 47434534466560 optimizer_v2.py:1043] Gradients do not exist for variables ['bert_with_mask/tf_ber

14813/14813 [==============================] - 2414s 163ms/step - loss: 9.3840 - val_loss: 9.3408
Epoch 2/10
 7872/14813 [==============>...............] - ETA: 18:36 - loss: 9.3415

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



12288/14813 [=======================>......] - ETA: 6:44 - loss: 9.3392

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



14813/14813 [==============================] - 2402s 162ms/step - loss: 9.3379 - val_loss: 9.3191
Epoch 3/10
 1999/14813 [===>..........................] - ETA: 33:53 - loss: 9.3304

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



 6523/14813 [============>.................] - ETA: 21:53 - loss: 9.3283

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



14813/14813 [==============================] - 2376s 160ms/step - loss: 9.3262 - val_loss: 9.3110
Epoch 4/10
10399/14813 [====================>.........] - ETA: 11:37 - loss: 9.3198

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



12164/14813 [=======================>......] - ETA: 6:59 - loss: 9.3193

In [ ]:
hist.history

In [ ]:
my_input = tokenize_string("I drove to <MASK> .")
my_output = model2((my_input, tf.ones(my_input.shape[:2], dtype=tf.bool) ))[0]

In [ ]:
tf.nn.top_k(my_output[0,4,:], 10)

In [ ]:
inv_tokenizer_lut = {v: k for k, v in my_tokenizer_lut.items()}
for t in range(7):
    print()
    print(f"t{t}:")
    for i in tf.nn.top_k(my_output[0,t,:], 5).indices.numpy():
        print(inv_tokenizer_lut[i])

# Save/Load model weights

In [ ]:
!rm -rf tinyBERT3
!mkdir tinyBERT3
model2.save_weights('tinyBERT3/tinyBERT', save_format='tf')

In [ ]:
# Recreate the model
new_model = bert_with_mask(config, onehot_mask)
new_model.compile(optimizer=optimizer, loss=loss)

# This initializes the variables used by the optimizers,
# as well as any stateful metric variables
new_model.train_on_batch(dataset.take(1))

# Load the state of the old model
new_model.load_weights('tinyBERT3/tinyBERT')

In [ ]:
my_input = tokenize_string("i drove to work")
my_output = new_model((my_input, tf.ones(my_input.shape[:2], dtype=tf.bool) ))[0]

In [ ]:
for i in range(7):
    print(inv_tokenizer_lut[my_input[0,i]])

In [ ]:
for t in range(7):
    print()
    print(f"t{t}:")
    for i, pct in zip(tf.nn.top_k(my_output[0,t,:], 2).indices.numpy(), tf.nn.top_k(my_output[0,t,:], 2).values.numpy()):
        print(f"Guess: {inv_tokenizer_lut[i]}, pct: {pct}")